services:

  reverse_proxy:
    image: traefik:2.3.0
    command:
      - --log.level=INFO
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --providers.docker

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    labels:
      traefik.http.routers.dash.rule: Host(`dash.localhost`)
      traefik.http.routers.dash.service: api@internal

    ports:
      - '80:80'


  website:
    image: web_static
    container_name: web_static_website
    labels:
      traefik.enable: true
      traefik.http.routers.website.rule: Host(`localhost`)
    deploy:
      replicas: 5
    depends_on:
      - reverse_proxy

  api:
    image: web_api
    container_name: web_api_container
    labels:
      traefik.enable: true
      traefik.http.routers.api.rule: Host(`localhost`) && PathPrefix(`/api`)
      traefik.http.services.api.loadBalancer.sticky.cookie: true
      traefik.http.services.api.loadBalancer.sticky.cookie.name: web_api_cookie
    deploy:
      replicas: 5
    depends_on:
      - reverse_proxy
